import uuid
from typing import Protocol

from app.models.galaxy import Galaxy


class GalaxyRepositoryPort(Protocol):
    """은하 영속성 기능 포트."""

    async def get_by_id(self, galaxy_id: uuid.UUID) -> Galaxy | None: ...

    async def get_by_user_and_slug(self, user_id: uuid.UUID, slug: str) -> Galaxy | None: ...

    async def list_by_user(self, user_id: uuid.UUID) -> list[Galaxy]: ...

    async def count_stars(self, galaxy_id: uuid.UUID) -> int: ...

    async def create(self, user_id: uuid.UUID, name: str, slug: str, color: str) -> Galaxy: ...

    async def update(self, galaxy: Galaxy, name: str | None, color: str | None) -> Galaxy: ...

    async def delete(self, galaxy: Galaxy) -> None: ...
